version: "2"
services:

  zookeeper-1:
    container_name: zookeeper-1    
    hostname: zookeeper-1.vnet
    networks:
      default:
        aliases:
          - zookeeper-1.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      
    command: -server 1 1 vnet

  namenode-1:
    container_name: namenode-1
    hostname: namenode-1.vnet
    networks:
      default:
        aliases:
          - namenode-1.vnet
    image: smizy/hadoop-base:2.7.6-alpine
    expose: ["8020"]
    ports:  ["50070"]
    environment:
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      - HADOOP_NAMENODE_HA=
      
    entrypoint: entrypoint.sh
    command: namenode-1

  datanode-1:
    container_name: datanode-1
    hostname: datanode-1.vnet
    networks:
      default:
        aliases:
          - datanode-1.vnet
    image: smizy/hadoop-base:2.7.6-alpine
    expose: ["50010", "50020", "50075"]
    environment:
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      - HADOOP_NAMENODE_HA=
      
    entrypoint: entrypoint.sh
    command: datanode

  hmaster-1:
    container_name: hmaster-1
    hostname: hmaster-1.vnet
    image: smizy/apache-phoenix:5.0.0-alpine
    networks:
      default:
        aliases:
          - hmaster-1.vnet
    expose: [16000]
    ports:  [16010]
    depends_on: ["zookeeper-1"]
    environment:
      - HBASE_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181

    volumes_from:
      - namenode-1
    volumes:
      - ./docker/hbase/conf:/usr/local/hbase-2.0.1/conf:rw,cached
    command: hmaster-1

  regionserver-1:
    container_name: regionserver-1
    hostname: regionserver-1.vnet
    image: smizy/apache-phoenix:5.0.0-alpine
    networks:
      default:
        aliases:
          - regionserver-1.vnet
    ports:
      - "5005:5005"
    expose:
      - 16020
      - 16030
    depends_on: ["zookeeper-1"]
    volumes:
      - ./meta_data:/root/meta_data:rw,cached
      - ../data:/root/data:rw,cached
      - ./docker/hbase/conf:/usr/local/hbase-2.0.1/conf:rw,cached
    environment:
      - HBASE_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181 
      
    command: regionserver

  queryserver-1:
    container_name: queryserver-1
    hostname: queryserver-1.vnet
    networks:
      default:
        aliases:
          - queryserver-1.vnet
    image: smizy/apache-phoenix:5.0.0-alpine
    ports: [8765]
    depends_on: ["zookeeper-1"]
    environment:
      - HBASE_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181 
    volumes:
      - ./docker/hbase/conf:/usr/local/hbase-2.0.1/conf:rw,cached
    command: bin/queryserver.py
